#!/bin/bash
cd "$(dirname "$0")"
set -a
source .env
set +a
echo "Starting build..."
dir_path=$(dirname "$BUILD_FOLDER/$BUILD_SCRIPT_TIMELINES")
rm -rf $PROD_FOLDER
rm -rf $BUILD_FOLDER
mkdir -p "$dir_path"
mkdir -p $PROD_FOLDER
cp -r $BASE_FOLDER/* $BUILD_FOLDER/
cd $BUILD_FOLDER
python3 build.py
cd ..
cp -r $BUILD_FOLDER/* $PROD_FOLDER/
rm -rf $BUILD_FOLDER
echo "Finished build"

./run
