#!/usr/bin/env bash
find tests -mindepth 1 ! -name 'backend-test.py' -exec rm -rf {} +
cp -r assets/* tests/
cd "$(dirname "$0")"
cd tests
../bin/python backend-test.py
cd ..
find tests -mindepth 1 ! -name 'backend-test.py' -exec rm -rf {} +
