#!/bin/bash
cd "$(dirname "$0")"
set -a
source .env
set +a
find $TEST_FOLDER -mindepth 1 ! -name 'backend-test.py' -exec rm -rf {} +
cp -r $BASE_FOLDER/* $TEST_FOLDER/
cd $TEST_FOLDER
python3 backend-test.py
cd ..
find $TEST_FOLDER -mindepth 1 ! -name 'backend-test.py' -exec rm -rf {} +
